### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by mlava** [Vaiterius/Monty-Pythons-Flying-API#1]
Hi there.
I am wanting to use your API, but get cors errors from everything except browser.
Is the fly.io API intended to be open?
Cheers!

**Comment by Vaiterius** [comment]
Hello, thanks for checking out my API. Could you describe the application and environment you are using to get requests from the API? Additional information on the errors you are getting would also be useful. The API is intended to be open to anyone that wishes to use it.

**Comment by mlava** [comment]
Of course, sorry.
I am able to go to https://monty-pythons-flying-api.fly.dev/v1/quotes/random in a browser and it works perfectly.
If I try to access with a simple javascript fetch from within Roam Research page or app I get a cors error.
Cheers!

**Comment by Vaiterius** [comment]
Could you also send a snippet of the code of how you are making the requests? CORS errors happen due to differences between the origin of API and the origin of the requester, and it depends on the how things are configured, what kind of data is being requested, the method used, etc. 

I'll have to reconfigure my app and add in some kind of CORS middleware. It would be preferable to reproduce this issue myself so I can test and debug.

**Comment by mlava** [comment]
Roam allows extensions which are basically javascript functions that run in browser.

The function I am calling is:

```
async function fetchMPFC() {
  const response = await fetch("https://monty-pythons-flying-api.fly.dev/v1/quotes/random");
  console.info(response);

  if (response.ok) {
    const data = await response.json();
    console.info(data);
    
// a bunch of data processing

    return (string);
    
  } else {
    console.error(data);
  }
}
```

**Comment by Vaiterius** [comment]
I went ahead and installed Roam Research and reproduced the issue with my changed code.

My console errors went from:
![image](https://user-images.githubusercontent.com/70365928/228130742-d74957a8-04e0-4ddc-90f8-dd283a8fd35e.png)

to:
![image](https://user-images.githubusercontent.com/70365928/228130781-436e7499-63b9-406a-a820-0a7af77d4cfc.png)

Can you check with yours now?

**Comment by mlava** [comment]
No more errors.
That is some pretty impressive user service... thank you!
